[package]
name = "loot-condition-interpreter"
version = "2.2.1"
authors = ["Oliver Hamlet <oliver@ortham.io>"]
license = "MIT"
edition = "2018"

[dependencies]
crc32fast = "1.2.0"
esplugin = "3.0.0"
nom = "7.0.0"
pelite = "0.9.0"
regex = "1.0.5"
unicase = "2.2.0"

[dev-dependencies]
criterion = "0.3.0"
tempfile = "3.0.0"

[[bench]]
name = "eval"
harness = false

[workspace]
members = ["ffi"]
