[package]
name = "loot-condition-interpreter"
version = "4.0.1"
authors = ["Oliver Hamlet <oliver@ortham.io>"]
license = "MIT"
edition = "2021"

[dependencies]
crc32fast = "1.4.2"
esplugin = "6.1.0"
nom = "7.0.0"
pelite = "0.10.0"
regex = "1.11.0"
unicase = "2.2.0"

[dev-dependencies]
criterion = "0.5.0"
tempfile = "3.13.0"

[[bench]]
name = "eval"
harness = false

[workspace]
members = ["ffi"]
