[package]
name = "loot-condition-interpreter"
version = "4.0.2"
authors = ["Oliver Hamlet <oliver@ortham.io>"]
license = "MIT"
edition = "2021"

[dependencies]
crc32fast = "1.4.2"
esplugin = "6.1.1"
nom = "7.0.0"
pelite = "0.10.0"
regex = "1.11.1"
unicase = "2.8.1"

[dev-dependencies]
criterion = "0.5.0"
tempfile = "3.14.0"

[[bench]]
name = "eval"
harness = false

[workspace]
members = ["ffi"]
