
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.esplugin]
url = "https://raw.githubusercontent.com/Ortham/esplugin/refs/heads/master/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[policy.loot-condition-interpreter]
audit-as-crates-io = false

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.crc32fast]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.criterion]]
version = "0.7.0"
criteria = "safe-to-run"

[[exemptions.criterion-plot]]
version = "0.6.0"
criteria = "safe-to-run"

[[exemptions.crossbeam-deque]]
version = "0.8.6"
criteria = "safe-to-run"

[[exemptions.dataview]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.derive_pod]]
version = "0.1.2"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.11"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.js-sys]]
version = "0.3.77"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.linux-raw-sys]]
version = "0.9.4"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-deploy"

[[exemptions.no-std-compat]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.nom]]
version = "8.0.0"
criteria = "safe-to-deploy"

[[exemptions.oorandom]]
version = "11.1.5"
criteria = "safe-to-run"

[[exemptions.pelite]]
version = "0.10.0"
criteria = "safe-to-deploy"

[[exemptions.pelite-macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.plotters]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-backend]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.plotters-svg]]
version = "0.3.7"
criteria = "safe-to-run"

[[exemptions.r-efi]]
version = "5.2.0"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.regex]]
version = "1.11.2"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.0.5"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.wasi]]
version = "0.14.2+wasi-0.2.4"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.wasm-bindgen]]
version = "0.2.100"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.wasm-bindgen-backend]]
version = "0.2.100"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.wasm-bindgen-macro]]
version = "0.2.100"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.100"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.wasm-bindgen-shared]]
version = "0.2.100"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-run"
suggest = false
notes = "At time of review this was only built if targeting WASM, which is not an intended target."

[[exemptions.winapi]]
version = "0.3.9"
criteria = "safe-to-deploy"

[[exemptions.winapi-i686-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.winapi-x86_64-pc-windows-gnu]]
version = "0.4.0"
criteria = "safe-to-deploy"
